// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function usable(value: string | undefined): string | undefined {
  if (!value || value.includes("REPLACE-AFTER-DASHBOARD-RESET"))
    return undefined;
  return value;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url:
      usable(process.env["SUPABASE_DB_MIGRATE_URL"]) ??
      process.env["SUPABASE_DB_STAFF_URL"] ??
      "",
  },
});
