import QRCode from "qrcode";

/**
 * Server-side QRIS QR renderer.
 *
 * Replaces the third-party HF Space (`larabert-qrgen.hf.space`) that used to
 * turn a Casaku `qr_string` into an image. Rendering locally removes a
 * single-point-of-failure from the checkout money path: the QR image is
 * generated by our own server, so a provider outage on that HF Space can no
 * longer block a customer from scanning and paying.
 *
 * This module MUST only be imported from server code (route handlers, server
 * actions). The `qrcode` dependency is not shipped to the browser.
 */

export type QrRenderSize = 200 | 300 | 500;

export const QR_RENDER_SIZES: readonly QrRenderSize[] = [200, 300, 500];

export class QrRenderError extends Error {
  readonly reason: "invalid_data" | "render_failed";
  constructor(reason: QrRenderError["reason"], message: string) {
    super(message);
    this.name = "QrRenderError";
    this.reason = reason;
  }
}

// QRIS payloads are EMV/ASCII strings. Reject anything outside printable ASCII
// (and cap length) so this endpoint cannot be abused as a resource oracle.
const QR_DATA_PATTERN = /^[\x20-\x7E]{8,4096}$/;

export function isValidQrData(data: unknown): data is string {
  return typeof data === "string" && QR_DATA_PATTERN.test(data);
}

export function parseQrSize(raw: unknown): QrRenderSize {
  const n = Number(raw);
  return (QR_RENDER_SIZES as readonly number[]).includes(n)
    ? (n as QrRenderSize)
    : 300;
}

/**
 * Renders a QR code for `data` as a PNG buffer. `data` is the raw payment
 * string (Casaku `qr_string` / QRIS payload) — the same value a third-party
 * renderer would have received.
 */
export async function renderQrPng(
  data: string,
  size: QrRenderSize = 300,
): Promise<Buffer> {
  if (!isValidQrData(data)) {
    throw new QrRenderError(
      "invalid_data",
      "QR data must be 8-4096 printable ASCII characters",
    );
  }

  try {
    return await QRCode.toBuffer(data, {
      type: "png",
      width: size,
      margin: 2,
      errorCorrectionLevel: "M",
      color: { dark: "#111111", light: "#ffffff" },
    });
  } catch (error) {
    throw new QrRenderError(
      "render_failed",
      error instanceof Error ? error.message : "QR rendering failed",
    );
  }
}
